language: generic
sudo: required
dist: trusty
services:
  - docker

matrix:
  include:
    - os: linux
      env: TARGET=i686-unknown-linux-gnu DOCKER=alexcrichton/rust-slave-dist:2015-10-20b
    - os: linux
      env: TARGET=x86_64-unknown-linux-gnu DOCKER=alexcrichton/rust-slave-dist:2015-10-20b
    - os: osx
      env: TARGET=x86_64-apple-darwin

install:
  - export PATH="$PATH:$HOME/.cargo/bin"
  - bash .ci/install.sh

script:
  - mkdir target
  - if [ ! -z "$DOCKER" ]; then
      docker run
        --entrypoint bash
        -u `id -u`:`id -g`
        -v $HOME/rust:/travis-rust:ro
        -v `pwd`:/buildslave:ro
        -v `pwd`/target:/buildslave/target
        -e TARGET=$TARGET
        -e SKIP_TESTS=$SKIP_TESTS
        -it $DOCKER
        .ci/build-docker.sh;
    else
      PATH=$HOME/rust/bin:$PATH sh .ci/build.sh;
    fi

cache:
  directories:
    - $HOME/.cargo
    - $TRAVIS_BUILD_DIR/target

deploy:
  provider: script
  script: .ci/deploy.sh
  skip_cleanup: true
  on:
    tags: true
