language: generic

matrix:
  include:
    - env: TARGET=i686-unknown-linux-gnu
      addons:
        apt:
          packages: *i686


install:
  - export PATH="$PATH:$HOME/.cargo/bin"
  - export STAGING_DIR="$HOME/openwrt"
  - bash .ci/install.sh
  - export PATH="$PATH:$(find $STAGING_DIR -maxdepth 1 -name 'toolchain*' -print -quit)/bin"

script:
  - bash .ci/script.sh
