language: generic

addons:
  apt:
    packages:
      - gcc-multilib
      - libssl-dev

matrix:
  include:
    - env: TARGET=i686-unknown-linux-gnu
      addons:
        apt:
          packages:
            - libssl-dev:i386
            - gcc-4.6-multilib
            - ia32-libs

    - env: TARGET=x86_64-unknown-linux-gnu
    #- env: TARGET=x86_64-apple-darwin

install:
  - export PATH="$PATH:$HOME/.cargo/bin"
  - bash .ci/install.sh

script:
  - bash .ci/script.sh
