language: generic

addons:
  apt:
    packages: gcc-multilib

matrix:
  include:
    - env: TARGET=i686-unknown-linux-gnu
    - env: TARGET=x86_64-unknown-linux-gnu

install:
  - export PATH="$PATH:$HOME/.cargo/bin"
  - bash .ci/install.sh

script:
  - bash .ci/script.sh
