cache:
  - 'target -> appveyor.yml'
  - 'vendor -> appveyor.yml'
  - '%USERPROFILE%\.cargo'

environment:
  TARGET: i686-pc-windows-msvc
  GITHUB_AUTH_TOKEN:
    secure: OIMAVZAsCzaNv3emTg9MlxxuA0vi2lwJM41cEtTjb9p1CQbDEO3riYwcVzLDjhZi

install:
  - set PATH=C:\Program Files\Git\mingw64\bin;%PATH%
  # Install rust, x86_64-pc-windows-msvc host
  # FIXME: switch back to win.rustup.rs
  - curl -sSf -o rustup-init.exe https://dev-static.rust-lang.org/rustup/dist/i686-pc-windows-gnu/rustup-init.exe
  - rustup-init.exe -y
  - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
  - rustup default stable-%TARGET%

  # let's see what we got
  - where rustc cargo
  - rustc -vV
  - cargo -vV
  - set CARGO_TARGET_DIR=%CD%\target

build: false

test_script:
  - cargo build --release --target i686-pc-windows-msvc

after_test:
  - powershell -File .ci/deploy.ps1
