[package]
name = "sentry-cli"
version = "1.2.0"
authors = ["Armin Ronacher <armin.ronacher@active-4.com>"]
build = "build.rs"

[dependencies]
clap = { version = "2.22", default-features = false, features = ["suggestions", "wrap_help"] }
error-chain = "0.10"
serde = "0.9"
serde_json = "0.9"
serde_derive = "0.9"
url = "1.4"
uuid = { version = "0.4", features = ["v4"] }
walkdir = "1.0"
which = "1.0"
zip = "0.2"
sha1 = "0.2.0"
itertools = "0.5"
rust-ini = "0.10"
open = "1.2"
runas = "0.1"
log = "0.3"
term = "0.4"
curl = "0.4.6"
might-be-minified = "0.1"
sourcemap = "1.0.0"
backtrace = "0.3.0"
plist = "0.1.2"
if_chain = "^0.1.2"
chrono = { version = "^0.3.0", features = ["serde"] }
regex = "0.2"
lazy_static = "0.2.4"
pbr = "0.3.1"
dotenv = "0.10.0"
elementtree = "0.1.1"
prettytable-rs = "0.6.0"
git2 = "0.6.4"

[replace.'curl:0.4.6']
git = "https://github.com/alexcrichton/curl-rust"
rev = "a204473f1679330058cb518b27ce1ebb7fe8a91f"

[replace.'curl-sys:0.3.10']
git = "https://github.com/alexcrichton/curl-rust"
rev = "a204473f1679330058cb518b27ce1ebb7fe8a91f"

[target.'cfg(not(windows))'.dependencies]
chan = "0.1"
chan-signal = "0.2"
openssl-probe = "0.1.0"

[target.'cfg(target_os="macos")'.dependencies]
osascript = "0.2"
unix-daemonize = "0.1"
