[package]
name = "sentry-cli"
version = "0.9.0"
authors = ["Armin Ronacher <armin.ronacher@active-4.com>"]

[lib]
name = "sentrycli"
path = "src/sentrycli/lib.rs"

[[bin]]
name = "sentry-cli"

[dependencies]
chan = "0.1.14"
chan-signal = "0.1.5"
clap = { version = "2.5.1", default-features = false, features = ["suggestions", "wrap_help"] }
hyper = "0.8.0"
mime = "^0.2"
mime_guess = "1.6.1"
multipart = "0.6.0-alpha"
serde = "0.7.5"
serde_json = "0.7.1"
serde_macros = "0.7.5"
url = "0.5.4"
uuid = "0.1.18"
walkdir = "0.1.5"
which = "0.1.0"
zip = "0.1.15"
sha1 = "0.1.1"
rust-ini = "0.9.4"
sourcemap = { git = "https://github.com/mitsuhiko/rust-sourcemap", default-features = false, features = ["nightly"] }
