[package]
name = "sentry-cli"
version = "0.16.0"
authors = ["Armin Ronacher <armin.ronacher@active-4.com>"]
build = "build.rs"

[lib]
name = "sentrycli"
path = "src/sentrycli/lib.rs"

[[bin]]
name = "sentry-cli"

[dependencies]
clap = { version = "2.9.2", default-features = false, features = ["suggestions", "wrap_help"] }
serde = "0.7.5"
serde_json = "0.7.1"
serde_macros = "0.7.5"
url = "1.1.1"
uuid = "0.1.18"
walkdir = "0.1.5"
which = "0.1.0"
zip = "0.1.15"
sha1 = "0.2.0"
itertools = "0.4.15"
rust-ini = "0.9.5"
open = "1.1.1"
runas = "0.1.0"
curl = { git = "https://github.com/alexcrichton/curl-rust", rev = "8b4a2273d6a271715b049e9731c18a3ff7b5b19a" }
sourcemap = { version = "0.3.1", default-features = false, features = ["nightly"] }

[target."cfg(not(windows))".dependencies]
chan = "0.1.14"
chan-signal = "0.1.5"
