[package]
name = "sentry-cli"
version = "1.14.0"
authors = ["Armin Ronacher <armin.ronacher@active-4.com>"]
build = "build.rs"

[dependencies]
clap = { version = "2.22", default-features = false, features = ["suggestions", "wrap_help"] }
error-chain = "0.10"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
url = "1.4"
uuid = { version = "0.5", features = ["v4", "serde"] }
walkdir = "1.0"
which = "1.0"
zip = "0.2"
sha1 = "0.2.0"
itertools = "0.6.0"
rust-ini = "0.10"
open = "1.2"
runas = "0.1"
log = "0.3"
curl = "0.4.6"
might-be-minified = "0.2.1"
sourcemap = "1.0.1"
backtrace = "0.3.0"
plist = "0.2.2"
if_chain = "^0.1.2"
chrono = { version = "^0.3.1", features = ["serde"] }
regex = "0.2"
lazy_static = "0.2.4"
indicatif = "0.5.0"
console = "0.4.2"
dotenv = "0.10.0"
prettytable-rs = "0.6.0"
humansize = "^1.0.0"
java-properties = "1.0.0"
mach_object = "^0.1.5"
memmap = "^0.5.0"
glob = "0.2.11"
libc = "0.2.23"
proguard = "0.3.0"
elementtree = "0.5.0"
# As we currently do not need to use any of the networking features of
# git2 (we only need local repo access) we can safely disable the default
# features and use nothing instead.
git2 = { version = "0.6.4", default-features = false, features = [] }

[replace.'curl:0.4.6']
git = "https://github.com/alexcrichton/curl-rust"
rev = "9af0dbb6d0859a91e48af1d1d9777ae75c62dc1b"

## This is currently disabled because we are not using any of the networking
## features of git2.  If the default features are enabled there this
## replacement is necessary.
#[replace.'curl-sys:0.3.10']
#git = "https://github.com/alexcrichton/curl-rust"
#rev = "a204473f1679330058cb518b27ce1ebb7fe8a91f"

[target.'cfg(not(windows))'.dependencies]
chan = "0.1"
chan-signal = "0.2"
openssl-probe = "0.1.0"

[target.'cfg(target_os="macos")'.dependencies]
osascript = "0.3"
unix-daemonize = "0.1"
mac-process-info = "0.1.0"

[profile.dev]
codegen-units = 2
