[package]
name = "sentry-cli"
version = "0.1.0"
authors = ["Armin Ronacher <armin.ronacher@active-4.com>"]

[lib]
name = "sentrycli"
path = "src/sentrycli/lib.rs"

[[bin]]
name = "sentry-cli"

[dependencies]
clap = { version = "2.0.5", default-features = false, features = ["suggestions"] }
hyper = "0.7.2"
mime = "0.1.1"
multipart = "0.3.1"
serde = "0.6.11"
serde_json = "0.6.0"
serde_macros = "0.6.11"
url = "0.5.4"
uuid = "0.1.18"
walkdir = "0.1.5"
zip = "0.1.15"
